services:
  - type: web
    name: auto-job-applier-ui
    env: python
    plan: starter
    branch: main
    region: oregon
    repo: https://github.com/marko-galesic/Auto_job_applier_linkedIn
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      rm -rf /var/lib/apt/lists/*
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: APPLICATION_HISTORY_DIR
        value: "all excels"
